Allegiance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('judiciary.urls'))

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

judiciary/urls.py
from django.urls import path
from . import views
from . views import CriminalCreateView, CriminalDeleteView, CriminalListView, CriminalUpdateView, CriminalDetailView

app_name = 'judiciary'

urlpatterns = [
    path('add_criminal/', CriminalCreateView.as_view(), name='add_criminal'),
    path('', CriminalListView.as_view(), name='index'),
    path('<int:pk>/delete/', CriminalDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', CriminalUpdateView.as_view(), name='update'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('<int:pk>', CriminalDetailView.as_view(), name='more'),
]

judiciary/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse


# Create your models here.
class Criminal(models.Model):
    firstname = models.CharField(max_length=20)
    middlename = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    mugshot = models.FileField()
    mugshot_no = models.IntegerField()
    fingerprint = models.FileField()
    sentence_date = models.DateTimeField(default=timezone.now())
    felony_description = models.TextField()
    sentencing_description = models.TextField()
    prisonname = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('judiciary:index')


    def __str__(self):
        return self.firstname

judiciary/forms.py
from django import forms
from . models import Criminal
from django.contrib.auth.models import User


class CriminalForm(forms.ModelForm):
     class Meta:

        model = Criminal
        fields = '__all__'

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

judiciary/views.py
from django.shortcuts import render, reverse, redirect
from . models import Criminal
from . forms import CriminalForm, UserForm
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, DetailView
from django.contrib.auth import login, logout, authenticate



# Create your views here.

class CriminalCreateView(CreateView):

    model = Criminal

    fields = ['firstname', 'middlename', 'lastname', 'mugshot', 'mugshot_no', 'fingerprint', 'sentence_date', 'felony_description', 'sentencing_description', 'prisonname']

    def get_success_url(self):
        return reverse('judiciary:index')

class CriminalUpdateView(UpdateView):
    model = Criminal

    fields = ['firstname', 'middlename', 'lastname', 'mugshot', 'mugshot_no', 'fingerprint', 'sentence_date', 'felony_description', 'sentencing_description', 'prisonname']

    def get_success_url(self):
        return reverse('judiciary:index')

    def form_valid(self, form):
        return super().form_valid(form)

class CriminalDeleteView(DeleteView):
    model = Criminal
    success_url = '/'


class CriminalListView(ListView):

    model = Criminal
    template_name = 'judiciary/index.html'
    context_object_name = 'criminals'

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                criminals = Criminal.objects.filter(user=request.user)
                return render(request, 'judiciary/index.html', {'criminals': criminals})

    return render(request, 'judiciary/register.html', {'form': form})

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                criminals = Criminal.objects.all()
                return render(request, 'judiciary/index.html', {'criminals': criminals})
    return render(request, 'judiciary/login.html')

def logout_user(request):
    logout(request)
    return redirect('judiciary:login_user')

class CriminalDetailView(DetailView):

    model = Criminal
    template_name = 'judiciary/more.html'
    context_object_name = 'criminal'

judiciary/templates/judiciary/add_criminal.html
{% extends 'judiciary/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      xmlns="http://www.w3.org/1999/html">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="text-default">Add Criminal</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                         <div class="row">
                             <table class="table">
                                 <thead><th>First Name</th><th>Middle Name</th><th>Last Name</th><th>Mug Shot</th><th>Mugshot No</th><th>Finger print</th><th>Sentence Date</th><th>Felony Description</th><th>Sentencing Descprition</th><th>Prison Name</th><th>Action</th></thead>
                                <tbody>
                                   {% if criminals %}
                                      {% for criminal in criminals %}
                                          <tr>
                                            <td>{{ criminal.firstname }}</td>
                                            <td>{{ criminal.middlename }}</td>
                                            <td>{{ criminal.lastname}}</td>
                                            <td><img src="{{ criminal.mugshot.url }}" alt="" style="height: 100px; width: 100px"></td>
                                            <td>{{ criminal.mugshot_no }}</td>
                                            <td><img src="{{ criminal.fingerprint.url }}" alt="" style="height: 100px; width: 50px"></td>
                                            <td>{{ criminal.sentence_date }}</td>
                                            <td>{{ criminal.felony_description }}</td>
                                            <td>{{ criminal.sentencing_description}}</td>
                                            <td>{{ criminal.prisonname }}</td>
                                            <td><a href="{% url 'judiciary:update' criminal.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-pencil"></span>Add</a> <a href="{% url 'judiciary:delete' criminal.id %}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span>Delete</a>  </td>
                                          </tr>
                                      {% endfor %}
                                   {% endif %}
                                </tbody>
                             </table>
                         </div>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

judiciary/templates/judiciary/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    </head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">PENTAGON</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li> <a href="{% url 'judiciary:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Criminal's Database
                    </a>
                </li>

            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'judiciary:add_criminal' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Records
                    </a>
                </li>
                {% if user.is_authenticated %}

                <li>
                    <a href="{% url 'judiciary:logout_user' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Log out
                    </a>
                </li>
                {% else %}

                <li>
                    <a href="{% url 'judiciary:login_user' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Log in
                    </a>
                </li>
                {% endif%}
            </ul>

        </div>

    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

judiciary/templates/judiciary/criminal_confirm_delete.html
{% extends 'judiciary/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      xmlns="http://www.w3.org/1999/html">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="text-default">DELETE</h3>
                </div>
            <form method="post" action="" enctype="multipart/form-data">


              {% csrf_token %}
              {{ form|crispy }}

              Are you sure you want to DELETE?



              <button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span>DELETE</button>


            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

judiciary/templates/judiciary/criminal_form.html
{% extends 'judiciary/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      xmlns="http://www.w3.org/1999/html">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="text-default">{% if object %}Update{% else %}Add records{% endif %}</h3>
                </div>
                <div class="panel-body">
                  <form method="post" action="" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ form|crispy }}
                      <div class="form-group">
                          <br>
                          <button type="submit" class="btn btn-primary">Add</button>
                      </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

judiciary/templates/judiciary/form_templates.html
{% block content %}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="criminal_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
{% endblock %}

judiciary/templates/judiciary/index.html
{% extends 'judiciary/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      xmlns="http://www.w3.org/1999/html">

<div class="container">
    <div class="row">
        <div class="page-header">
            <h3 class="text-center text-primary">PENTAGON</h3>
        </div>
    </div>
    <div class="row">
        <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
         <table class="table">

             <thead><th>First Name</th><th>Middle Name</th><th>Last Name</th><th>Mug Shot</th><th>Prison Name</th><th>Action</th></thead>
            <tbody>
               {% if criminals %}
                  {% for criminal in criminals %}
                      <tr>
                        <td>{{ criminal.firstname }}</td>
                        <td>{{ criminal.middlename }}</td>
                        <td>{{ criminal.lastname}}</td>
                        <td><img src="{{ criminal.mugshot.url }}" alt="" style="height: 100px; width: 100px"></td>
                        <td>{{ criminal.prisonname }}</td>
                        <td><a href="{% url 'judiciary:update' criminal.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-pencil"></span>Update</a> <a href="{% url 'judiciary:delete' criminal.id %}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span>Delete</a> <a href="{% url 'judiciary:more' criminal.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-pencil"></span>More </a> </td>

                      </tr>
                  {% endfor %}
               {% endif %}
            </tbody>
         </table>
        </form>
    </div>
</div>
{% endblock %}

judiciary/templates/judiciary/login.html
{% extends 'judiciary/base.html' %}

{% block content %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="panel-heading">
                <h3>Login</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Username</label>
                        <input type="text" class="form-control" name="username">
                    </div>

                    <div class="form-group">
                         <label class="control-label">password</label>
                        <input type="password" class="form-control" name="password">

                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>

                    <div>

                        <p> Not Registered? <a href="{% url 'judiciary:register' %}">Register</a></p>

                    </div>



                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

judiciary/templates/judiciary/more.html
{% extends 'judiciary/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      xmlns="http://www.w3.org/1999/html">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="text-default">Criminal's Details</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                         <div class="row">
                             <table class="table">
                                <thead><th>First Name</th><th>Middle Name</th><th>Last Name</th><th>Mug Shot</th><th>Mugshot No</th><th>Finger print</th><th>Sentence Date</th><th>Felony Description</th><th>Sentencing Descprition</th><th>Prison Name</th></thead>
                                <tbody>

                                          <tr>
                                            <td>{{ criminal.firstname }}</td>
                                            <td>{{ criminal.middlename }}</td>
                                            <td>{{ criminal.lastname}}</td>
                                            <td><img src="{{ criminal.mugshot.url }}" alt="" style="height: 100px; width: 100px"></td>
                                            <td>{{ criminal.mugshot_no }}</td>
                                            <td><img src="{{ criminal.fingerprint.url }}" alt="" style="height: 100px; width: 50px"></td>
                                            <td>{{ criminal.sentence_date }}</td>
                                            <td>{{ criminal.felony_description }}</td>
                                            <td>{{ criminal.sentencing_description}}</td>
                                            <td>{{ criminal.prisonname }}</td>
                                          </tr>

                                </tbody>
                             </table>
                         </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

judiciary/templates/judiciary/prac.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<label for="fname">Name</label>
<p id="fname">{{criminal.firstname}}</p>

</body>
</html>

judiciary/templates/judiciary/register.html
{% extends 'judiciary/base.html' %}
{% block content %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="text-default">Register</h3>
                    </div>
                    <div class="panel-body">
                      <form method="post" action="" enctype="multipart/form-data">
                          {% csrf_token %}
                          {% include 'judiciary/form_templates.html' %}
                          <div class="form-group">
                              <br>
                              <button type="submit" class="btn btn-primary">Add</button>

                          </div>
                            <div>

                            <p> Already Registered? <a href="{% url 'judiciary:login_user' %}">Login</a> </p>

                             </div>

                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}